### PR TITLE
Added acknowledgments

### PR DESCRIPTION
**Pull request by alexec**

### CODE REVIEW

**Comment by alexec** [comment]
@yujunliang just spent 30 mins fixing the issues. Added some acknowledgements too.

**Comment by yujunliang** [comment]
I saw you did a lot of work! Thank you.

Happy new year!

Regards
Yujun
(347) 949 8586

On Dec 30, 2016, at 6:58 AM, Alex Collins <notifications@github.com<mailto:notifications@github.com>> wrote:


Reopened #26<https://github.com/selenium-webdriver-book/manuscript/pull/26>.

-

**Comment by PulwerJR** [comment]
You’re very welcome. It’s always nice to be able to make a contribution.

If you do put a mention of me in the Foreward or Acknowlegements section, here is the correct spelling of my name: John Pulwers

**Comment by PulwerJR** [comment]
Any Acknowledgements…please use name: John Pulwers

**Pull request merged**
